name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  PATH: C:\Windows\System32;C:\Windows\SysWOW64\WindowsPowerShell\v1.0;D:\a\msys64\clang64\bin;D:\a\msys64\usr\bin
  env_var: ${{ secrets.SEKRET001 }}
jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    #runs-on: windows-latest
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        sys: [ CLANG64 ]
        #sys: [ MINGW64, MINGW32, UCRT64, CLANG64 ]
#    defaults:
#      run:
#        shell: msys2 {0}

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        msystem: clang64 
        path-type: strict
        location: D:\a
#        release: false
#        update: true
        install: >-
          git
#          p7zip
#          zip
#          unrar
#          cmake
#          base-devel
          
        pacboy: >-
          cmake:p
          clang:p
          ninja:p
#          lldb:p
#          gdb:p
#          graphviz:p

    - shell: msys2 {0}
      run: |
        set
        ls -la 
        pwd
        ls -la /clang64
        ls -la /clang64/bin
        
      
    - uses: actions/checkout@v3

#    - shell: msys2 {0} 
#      run: |
#        /clang64/bin/cmake.exe -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        
    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C ${{env.BUILD_TYPE}}

